Add Prokka
proksee-project/proksee-cmd pull request #73
Opened 2022-05-19 15:20 UTC by emarinier

Note: merging into dev/annotate instead of develop. Mostly as a way to contain all the annotate stuff while we work it out.

Adds Prokka functionality.

2022-06-09 16:32 UTC, ericenns requested changes
This looks good, just a minor comment

2022-06-09 16:32 UTC, ericenns commented on proksee/pipelines/annotate.py
> +    output = prokka_annotator.annotate()
The name `output` here confused me a bit since it not quite the console output and neither is it the tools outputs. I'm not sure I have a great suggestion on what to name this. I had to look at `prokka_annotator.py` to understand what `output` is.

2022-06-14 15:47 UTC, emarinier commented on proksee/pipelines/annotate.py
> +    output = prokka_annotator.annotate()
I've change it to the following:

**prokka_annotator.annotate()**

```
message = "Annotations complete and located in " + str(self.prokka_output_directory) + "."

return message
```

**annotate.annotate()**

```
prokka_annotator = ProkkaAnnotator(contigs_filename, output_directory, resource_specification)
pipeline_message = prokka_annotator.annotate()
print(pipeline_message + "\n")
```

2022-06-16 16:38 UTC, ericenns approved these changes
👍 looks good to me!

2022-06-16 16:39 UTC, merged